export{default as SignUp} from './SignUp'
export {default as SignIn} from './SignIn'
export {default as Quests} from './Quests'
export {default as Location} from './Location'
export {default as Employee} from './Employee'
export {default as ListEmployee} from './ListEmployee'
export {default as Landing} from './Landing'
export {default as Ask} from './Asks'
export {default as Main} from './Main'
